version: "1.0"
services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres_data_students:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=students
    ports:
        - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  students:
    build:
      context: .
      dockerfile: students_svc/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/students?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    command: [ "/app/main" ]
  postgres_courses:
    image: postgres:14-alpine
    volumes:
      - postgres_data_courses:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=courses
    ports:
        - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_courses"]
      interval: 5s
      timeout: 5s
      retries: 5
  courses:
    build:
      context: .
      dockerfile: courses_svc/Dockerfile
    ports:
      - "7071:7071"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres_courses:5432/courses?sslmode=disable
    depends_on:
      postgres_courses:
        condition: service_healthy
    links:
      - postgres_courses
    command: [ "/app/main" ]
volumes:
  postgres_data_courses:
  postgres_data_students:
