// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"time"
)

type Enrollment struct {
	ID             int64
	StudentID      int64
	CourseID       int64
	EnrollmentDate time.Time
	CreatedAt      time.Time
}

type Student struct {
	ID          int64
	Fullname    string
	DateOfBirth time.Time
	// must be between 0 and 11
	Grade     int32
	Phone     int64
	CreatedAt time.Time
}
